#pragma once
#pragma pack(push,1)
typedef enum class XG_FORMAT {
	DXGI_FORMAT_UNKNOWN = 0,
	DXGI_FORMAT_R32G32B32A32_TYPELESS = 1,
	DXGI_FORMAT_R32G32B32A32_FLOAT = 2,
	DXGI_FORMAT_R32G32B32A32_UINT = 3,
	DXGI_FORMAT_R32G32B32A32_SINT = 4,
	DXGI_FORMAT_R32G32B32_TYPELESS = 5,
	DXGI_FORMAT_R32G32B32_FLOAT = 6,
	DXGI_FORMAT_R32G32B32_UINT = 7,
	DXGI_FORMAT_R32G32B32_SINT = 8,
	DXGI_FORMAT_R16G16B16A16_TYPELESS = 9,
	DXGI_FORMAT_R16G16B16A16_FLOAT = 10,
	DXGI_FORMAT_R16G16B16A16_UNORM = 11,
	DXGI_FORMAT_R16G16B16A16_UINT = 12,
	DXGI_FORMAT_R16G16B16A16_SNORM = 13,
	DXGI_FORMAT_R16G16B16A16_SINT = 14,
	DXGI_FORMAT_R32G32_TYPELESS = 15,
	DXGI_FORMAT_R32G32_FLOAT = 16,
	DXGI_FORMAT_R32G32_UINT = 17,
	DXGI_FORMAT_R32G32_SINT = 18,
	DXGI_FORMAT_R32G8X24_TYPELESS = 19,
	DXGI_FORMAT_D32_FLOAT_S8X24_UINT = 20,
	DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS = 21,
	DXGI_FORMAT_X32_TYPELESS_G8X24_UINT = 22,
	DXGI_FORMAT_R10G10B10A2_TYPELESS = 23,
	DXGI_FORMAT_R10G10B10A2_UNORM = 24,
	DXGI_FORMAT_R10G10B10A2_UINT = 25,
	DXGI_FORMAT_R11G11B10_FLOAT = 26,
	DXGI_FORMAT_R8G8B8A8_TYPELESS = 27,
	DXGI_FORMAT_R8G8B8A8_UNORM = 28,
	DXGI_FORMAT_R8G8B8A8_UNORM_SRGB = 29,
	DXGI_FORMAT_R8G8B8A8_UINT = 30,
	DXGI_FORMAT_R8G8B8A8_SNORM = 31,
	DXGI_FORMAT_R8G8B8A8_SINT = 32,
	DXGI_FORMAT_R16G16_TYPELESS = 33,
	DXGI_FORMAT_R16G16_FLOAT = 34,
	DXGI_FORMAT_R16G16_UNORM = 35,
	DXGI_FORMAT_R16G16_UINT = 36,
	DXGI_FORMAT_R16G16_SNORM = 37,
	DXGI_FORMAT_R16G16_SINT = 38,
	DXGI_FORMAT_R32_TYPELESS = 39,
	DXGI_FORMAT_D32_FLOAT = 40,
	DXGI_FORMAT_R32_FLOAT = 41,
	DXGI_FORMAT_R32_UINT = 42,
	DXGI_FORMAT_R32_SINT = 43,
	DXGI_FORMAT_R24G8_TYPELESS = 44,
	DXGI_FORMAT_D24_UNORM_S8_UINT = 45,
	DXGI_FORMAT_R24_UNORM_X8_TYPELESS = 46,
	DXGI_FORMAT_X24_TYPELESS_G8_UINT = 47,
	DXGI_FORMAT_R8G8_TYPELESS = 48,
	DXGI_FORMAT_R8G8_UNORM = 49,
	DXGI_FORMAT_R8G8_UINT = 50,
	DXGI_FORMAT_R8G8_SNORM = 51,
	DXGI_FORMAT_R8G8_SINT = 52,
	DXGI_FORMAT_R16_TYPELESS = 53,
	DXGI_FORMAT_R16_FLOAT = 54,
	DXGI_FORMAT_D16_UNORM = 55,
	DXGI_FORMAT_R16_UNORM = 56,
	DXGI_FORMAT_R16_UINT = 57,
	DXGI_FORMAT_R16_SNORM = 58,
	DXGI_FORMAT_R16_SINT = 59,
	DXGI_FORMAT_R8_TYPELESS = 60,
	DXGI_FORMAT_R8_UNORM = 61,
	DXGI_FORMAT_R8_UINT = 62,
	DXGI_FORMAT_R8_SNORM = 63,
	DXGI_FORMAT_R8_SINT = 64,
	DXGI_FORMAT_A8_UNORM = 65,
	DXGI_FORMAT_R1_UNORM = 66,
	DXGI_FORMAT_R9G9B9E5_SHAREDEXP = 67,
	DXGI_FORMAT_R8G8_B8G8_UNORM = 68,
	DXGI_FORMAT_G8R8_G8B8_UNORM = 69,
	DXGI_FORMAT_BC1_TYPELESS = 70,
	DXGI_FORMAT_BC1_UNORM = 71,
	DXGI_FORMAT_BC1_UNORM_SRGB = 72,
	DXGI_FORMAT_BC2_TYPELESS = 73,
	DXGI_FORMAT_BC2_UNORM = 74,
	DXGI_FORMAT_BC2_UNORM_SRGB = 75,
	DXGI_FORMAT_BC3_TYPELESS = 76,
	DXGI_FORMAT_BC3_UNORM = 77,
	DXGI_FORMAT_BC3_UNORM_SRGB = 78,
	DXGI_FORMAT_BC4_TYPELESS = 79,
	DXGI_FORMAT_BC4_UNORM = 80,
	DXGI_FORMAT_BC4_SNORM = 81,
	DXGI_FORMAT_BC5_TYPELESS = 82,
	DXGI_FORMAT_BC5_UNORM = 83,
	DXGI_FORMAT_BC5_SNORM = 84,
	DXGI_FORMAT_B5G6R5_UNORM = 85,
	DXGI_FORMAT_B5G5R5A1_UNORM = 86,
	DXGI_FORMAT_B8G8R8A8_UNORM = 87,
	DXGI_FORMAT_B8G8R8X8_UNORM = 88,
	DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM = 89,
	DXGI_FORMAT_B8G8R8A8_TYPELESS = 90,
	DXGI_FORMAT_B8G8R8A8_UNORM_SRGB = 91,
	DXGI_FORMAT_B8G8R8X8_TYPELESS = 92,
	DXGI_FORMAT_B8G8R8X8_UNORM_SRGB = 93,
	DXGI_FORMAT_BC6H_TYPELESS = 94,
	DXGI_FORMAT_BC6H_UF16 = 95,
	DXGI_FORMAT_BC6H_SF16 = 96,
	DXGI_FORMAT_BC7_TYPELESS = 97,
	DXGI_FORMAT_BC7_UNORM = 98,
	DXGI_FORMAT_BC7_UNORM_SRGB = 99,
	DXGI_FORMAT_AYUV = 100,
	DXGI_FORMAT_Y410 = 101,
	DXGI_FORMAT_Y416 = 102,
	DXGI_FORMAT_NV12 = 103,
	DXGI_FORMAT_P010 = 104,
	DXGI_FORMAT_P016 = 105,
	DXGI_FORMAT_420_OPAQUE = 106,
	DXGI_FORMAT_YUY2 = 107,
	DXGI_FORMAT_Y210 = 108,
	DXGI_FORMAT_Y216 = 109,
	DXGI_FORMAT_NV11 = 110,
	DXGI_FORMAT_AI44 = 111,
	DXGI_FORMAT_IA44 = 112,
	DXGI_FORMAT_P8 = 113,
	DXGI_FORMAT_A8P8 = 114,
	DXGI_FORMAT_B4G4R4A4_UNORM = 115,
	DXGI_FORMAT_P208 = 130,
	DXGI_FORMAT_V208 = 131,
	DXGI_FORMAT_V408 = 132,
	DXGI_FORMAT_SAMPLER_FEEDBACK_MIN_MIP_OPAQUE,
	DXGI_FORMAT_SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE,
	DXGI_FORMAT_FORCE_UINT = 0xffffffff
};


// source: https://learn.microsoft.com/en-us/windows/win32/api/d3d11/ne-d3d11-d3d11_bind_flag
// chance this doesn't match exactly
typedef enum XG_BIND_FLAG : UINT {
	XG_BIND_VERTEX_BUFFER = 0x1L,
	XG_BIND_INDEX_BUFFER = 0x2L,
	XG_BIND_CONSTANT_BUFFER = 0x4L,
	XG_BIND_SHADER_RESOURCE = 0x8L,
	XG_BIND_STREAM_OUTPUT = 0x10L,
	XG_BIND_RENDER_TARGET = 0x20L, // CONFIRMED
	XG_BIND_DEPTH_STENCIL = 0x40L, // CONFIRMED
	XG_BIND_UNORDERED_ACCESS = 0x80L,
	XG_BIND_DECODER = 0x200L,
	XG_BIND_VIDEO_ENCODER = 0x400L
};
// source: https://learn.microsoft.com/en-us/windows/win32/api/d3d11/ne-d3d11-d3d11_resource_misc_flag
// potentially incorrect
typedef enum XG_RESOURCE_MISC_FLAG : UINT {
	XG_RESOURCE_MISC_GENERATE_MIPS = 0x1L,
	XG_RESOURCE_MISC_SHARED = 0x2L,
	XG_RESOURCE_MISC_TEXTURECUBE = 0x4L,
	XG_RESOURCE_MISC_DRAWINDIRECT_ARGS = 0x10L,
	XG_RESOURCE_MISC_BUFFER_ALLOW_RAW_VIEWS = 0x20L,
	XG_RESOURCE_MISC_BUFFER_STRUCTURED = 0x40L,
	XG_RESOURCE_MISC_RESOURCE_CLAMP = 0x80L,
	XG_RESOURCE_MISC_SHARED_KEYEDMUTEX = 0x100L,
	XG_RESOURCE_MISC_GDI_COMPATIBLE = 0x200L,
	XG_RESOURCE_MISC_SHARED_NTHANDLE = 0x800L,
	XG_RESOURCE_MISC_RESTRICTED_CONTENT = 0x1000L,
	XG_RESOURCE_MISC_RESTRICT_SHARED_RESOURCE = 0x2000L,
	XG_RESOURCE_MISC_RESTRICT_SHARED_RESOURCE_DRIVER = 0x4000L,
	XG_RESOURCE_MISC_GUARDED = 0x8000L,
	XG_RESOURCE_MISC_TILE_POOL = 0x20000L,
	XG_RESOURCE_MISC_TILED = 0x40000L,
	XG_RESOURCE_MISC_HW_PROTECTED = 0x80000L,
	XG_RESOURCE_MISC_SHARED_DISPLAYABLE,
	XG_RESOURCE_MISC_SHARED_EXCLUSIVE_WRITER
};
// source: https://learn.microsoft.com/en-us/windows/win32/api/d3d11/ne-d3d11-d3d11_cpu_access_flag
typedef enum XG_CPU_ACCESS_FLAG {
	XG_CPU_ACCESS_WRITE = 0x10000L,
	XG_CPU_ACCESS_READ = 0x20000L
};
// source: DirectXTex.h : LINE 134 (it confirms these match elsewhere)
enum XG_RESOURCE_DIMENSION
{	// "Subset here matches D3D10_RESOURCE_DIMENSION and D3D11_RESOURCE_DIMENSION"
	XG_RESOURCE_DIMENSION_TEXTURE1D = 2,
	XG_RESOURCE_DIMENSION_TEXTURE2D = 3,
	XG_RESOURCE_DIMENSION_TEXTURE3D = 4,
};
enum XG_TILE_MODE : UINT {
	// unknown // placeholder
	XG_TILE_MODE_INVALID = 0,
	XG_TILE_MODE_LINEAR = 1,
};
typedef enum XG_USAGE {
	XG_USAGE_DEFAULT = 0,
	XG_USAGE_IMMUTABLE = 1,
	XG_USAGE_DYNAMIC = 2,
	XG_USAGE_STAGING = 3
};
typedef enum XG_TEXTURE_LAYOUT {
	XG_TEXTURE_LAYOUT_UNKNOWN = 0,
	XG_TEXTURE_LAYOUT_ROW_MAJOR = 1,
	XG_TEXTURE_LAYOUT_64KB_UNDEFINED_SWIZZLE = 2,
	XG_TEXTURE_LAYOUT_64KB_STANDARD_SWIZZLE = 3
};
typedef enum XG12_RESOURCE_MISC_FLAGS {
	XG12_RESOURCE_FLAG_NONE = 0,
	XG12_RESOURCE_FLAG_ALLOW_RENDER_TARGET = 0x1,
	XG12_RESOURCE_FLAG_ALLOW_DEPTH_STENCIL = 0x2,
	XG12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS = 0x4,
	XG12_RESOURCE_FLAG_DENY_SHADER_RESOURCE = 0x8,
	XG12_RESOURCE_FLAG_ALLOW_CROSS_ADAPTER = 0x10,
	XG12_RESOURCE_FLAG_ALLOW_SIMULTANEOUS_ACCESS = 0x20,
	XG12_RESOURCE_FLAG_VIDEO_DECODE_REFERENCE_ONLY = 0x40,
	XG12_RESOURCE_FLAG_VIDEO_ENCODE_REFERENCE_ONLY = 0x80,
	XG12_RESOURCE_FLAG_RAYTRACING_ACCELERATION_STRUCTURE = 0x100
};

// basis source: https://learn.microsoft.com/en-us/windows/win32/api/d3d11/ns-d3d11-d3d11_texture1d_desc
// accurate source: DirectXTexXboxTile.cpp : LINE 842, 202
typedef struct XG_TEXTURE1D_DESC{
	UINT Width;
	UINT MipLevels;
	UINT ArraySize;
	XG_FORMAT Format;
	XG_USAGE Usage;
	XG_BIND_FLAG BindFlags;
	XG_RESOURCE_MISC_FLAG MiscFlags;
	XG_TILE_MODE TileMode;
	UINT Pitch;
};

// source: SimpleESRAM.cpp : LINE 304
typedef struct XG_SAMPLE_DESC{
	UINT Count;
	UINT Qualtiy;
};

// basis source: https://learn.microsoft.com/en-us/windows/win32/api/d3d11/ns-d3d11-d3d11_texture2d_desc
// accurate source: SimpleESRAM.cpp : LINE 297
typedef struct XG_TEXTURE2D_DESC{
	UINT Width;
	UINT Height;
	UINT MipLevels;
	UINT ArraySize;
	XG_FORMAT Format;
	XG_SAMPLE_DESC SampleDesc;
	XG_USAGE Usage;
	XG_BIND_FLAG BindFlags;
	XG_CPU_ACCESS_FLAG CPUAccessFlags;
	XG_RESOURCE_MISC_FLAG MiscFlags;
	//UINT ESRAMOffsetBytes; // im pretty sure these are only for the ESRAM example
	//UINT ESRAMUsageBytes;
	XG_TILE_MODE TileMode;
	UINT Pitch;
};
// basis source: https://learn.microsoft.com/en-us/windows/win32/api/d3d11/ns-d3d11-d3d11_texture3d_desc
// accurate source: SimpleESRAM.cpp : LINE 297
typedef struct XG_TEXTURE3D_DESC {
	UINT Width;
	UINT Height;
	UINT Depth;
	UINT MipLevels;
	XG_FORMAT Format;
	XG_USAGE Usage;
	XG_BIND_FLAG BindFlags;
	XG_CPU_ACCESS_FLAG CPUAccessFlags;
	XG_RESOURCE_MISC_FLAG MiscFlags;
	XG_TILE_MODE TileMode;
	UINT Pitch;
};

typedef struct XG_RESOURCE_DESC{
	XG_RESOURCE_DIMENSION Dimension;
	UINT64 Alignment;
	UINT Width;
	UINT Height;
	UINT ArraySize;
	UINT MipLevels;
	XG_FORMAT Format;
	XG_SAMPLE_DESC SampleDesc;
	XG_TEXTURE_LAYOUT Layout;
	XG12_RESOURCE_MISC_FLAGS MiscFlags;
	// possibly pitch in here too
};

// NOT REAL STRUCT // USED TO GET THIS TO COMPILE //
typedef struct XG_mipmap{
	UINT WidthElements;
	UINT HeightElements;
	UINT PitchPixels;
	UINT PaddedDepthOrArraySize;
	UINT SizeBytes;
	UINT OffsetBytes;
	UINT PaddedHeightElements;
	UINT PaddedWidthElements;
	UINT PitchBytes;
	UINT Slice2DSizeBytes;
};
// NOT REAL STRUCT // USED TO GET THIS TO COMPILE //
typedef struct XG_plane{
	XG_mipmap* MipLayout;
	size_t BytesPerElement;
};

// size should be 1720 bytes (?) sourced from the decompiled 'GetResourceLayout' function
typedef struct XG_RESOURCE_LAYOUT {
	UINT SizeBytes; // im pretty sure this is right, judging by the decompiled code of the xg.dll
	// these are just to remove the errors
	UINT Planes;
	XG_plane* Plane;
	UINT Dimension;
	UINT MipLevels;
	UINT BaseAlignmentBytes;

};

class XGTextureAddressComputer
{
public:
	size_t GetTexelElementOffsetBytes(UINT s, UINT level, UINT x, UINT y, UINT arrayorslice, UINT sample); // REMAP THE INPUTS
	HRESULT GetResourceLayout(XG_RESOURCE_LAYOUT* layout);
	unsigned long Release();
};

bool LoadScanline(DirectX::XMVECTOR* tiled, UINT32 tiledPixels, const uint8_t* xboximg_ptr, UINT bitmap_sizebytes, DXGI_FORMAT format);
bool StoreScanline(uint8_t* pixels, size_t rowPitch, DXGI_FORMAT format, DirectX::XMVECTOR* target, size_t width);

HRESULT XGCreateTexture1DComputer(XG_TEXTURE1D_DESC* texdata, XGTextureAddressComputer** computer);
HRESULT XGCreateTexture2DComputer(XG_TEXTURE2D_DESC* texdata, XGTextureAddressComputer** computer);
HRESULT XGCreateTexture3DComputer(XG_TEXTURE3D_DESC* texdata, XGTextureAddressComputer** computer);

#pragma pack(pop)
/*
if (layout.Planes != 1)
return HRESULT_FROM_WIN32(ERROR_NOT_SUPPORTED);

if (layout.SizeBytes != xbox.GetSize()
	|| layout.BaseAlignmentBytes != xbox.GetAlignment())
	return E_UNEXPECTED; */